server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: john123
    url: jdbc:mysql://localhost:3306/hackathon?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 2000MB
      max-request-size: 2015MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database-platform: org.hibernate.MySQL5InnoDBDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: chattingapp001@gmail.com
    password: John@12345
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

